apiVersion: v1
kind: Pod
metadata:
  name: meu-pod
  labels:
    app: meu-pod
spec:
  containers:
    - name: girafa
      image: nginx:stable-alpine
      env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: meu-secret
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: meu-secret
              key: password
