apiVersion: v1
kind: Pod
metadata:
  name: webserver
  labels:
    run: webserver
spec:
  containers:
  - name: webserver-1
    image: nginx:alpine
    volumeMounts:
    - mountPath: "/giropops"
      name: primeiro-volume
    resources:
      requests:
        cpu: "500m"
        memory: "128Mi"
      limits:
        cpu: 1
        memory: "128Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: primeiro-volume
    emptyDir:
      sizeLimit: "256Mi"
