apiVersion: v1
kind: Pod
metadata:
  labels:
    run: poseidon
  name: poseidon
spec:
  containers:
  - image: nginx:stable-alpine
    name: poseidon
    ports:
    - containerPort: 80
    resources: 
      limits:
        cpu: "1"
        memory: 128Mi
      requests:
        cpu: "500m"
        memory: 64Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
