apiVersion: v1
kind: Service
metadata:
  labels:
    run: poseidon
  name: poseidon
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: poseidon
  type: NodePort
status:
  loadBalancer: {}
