apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rolling-update
  name: rolling-update
  namespace: narnia
spec:
  replicas: 5 
  selector:
    matchLabels:
      app: rolling-update
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2
  template:
    metadata:
      labels:
        app: rolling-update
    spec:
      containers:
      - image: nginx@sha256:284999d967248984ccd9fffa669c0c49b923e00de28d4c43f5b8c621d881eb44
        name: narnia
        resources:
          limits:
            cpu: 1
            memory: 128Mi
          requests:
            cpu: 1
            memory: 64Mi
