apiVersion: v1
kind: Service
metadata:
  name: nodeport-nginx
  labels:
    app: nginx
    env: production
spec:
  selector:
    app: girafa
  ports:
    - port: 80
      name: http
      targetPort: 80
      nodePort: 32000
  type: NodePort
